name: Manhunt
version: 1.0-SNAPSHOT
main: me.alanseyfir.manhunt.Main
api-version: 1.17
authors: [ AlanSeyfir ]
description: Manhunt minigame with compass
website: https://alanseyfir.github.io/personal-portfolio/
